import { useMemo } from 'react';

export default function useRows() {
  const rows = useMemo(
    () => [
      {
        firstSurname: 'Ruiz',
        lastSurname: 'Ruiz',
        name: 'Mauricio',
        email: 'ruizmauricio@gmail.com',
        phone: '1',
        status: 'A',
        subRows: [
          {
            firstSurname: 'Ruiz',
            lastSurname: 'Ruiz',
            name: 'Mauricio',
            email: 'ruizmauricio@gmail.com',
            phone: '1',
            status: 'A',
          },
        ],
      },
      {
        firstSurname: 'Pichi',
        lastSurname: 'Picih',
        name: 'Carrizo',
        email: 'pichica@gmail.com',
        phone: '2',
        status: 'A',
      },
      {
        firstSurname: 'Big',
        lastSurname: 'Fausto',
        name: 'Force',
        email: 'bigforce@gmail.com',
        phone: '3',
        status: 'B',
      },
      {
        firstSurname: 'Oliva',
        lastSurname: 'Olivia',
        name: 'Tutex',
        email: 'tutexa@gmail.com',
        phone: '4',
        status: 'A',
      },
      {
        firstSurname: 'Casc',
        lastSurname: 'ales',
        name: 'Benja',
        email: 'half500@gmail.com',
        phone: '5',
        status: 'B',
      },
      {
        firstSurname: 'Mejia',
        lastSurname: 'Salinas',
        name: 'Heather',
        email: '@icloud.couk',
        phone: '(587) 777-4737',
        status: 'A',
      },
      {
        firstSurname: 'Morton',
        lastSurname: 'Rice',
        name: 'Ora',
        email: '@outlook.ca',
        phone: '(736) 916-4741',
        status: 'A',
      },
      {
        firstSurname: 'Becker',
        lastSurname: 'Short',
        name: 'Ulric',
        email: '@protonmail.net',
        phone: '1-567-123-8723',
        status: 'A',
      },
      {
        firstSurname: 'Atkinson',
        lastSurname: 'Horton',
        name: 'Jin',
        email: '@icloud.org',
        phone: '1-427-382-5260',
        status: 'A',
      },
      {
        firstSurname: 'Bolton',
        lastSurname: 'Wiggins',
        name: 'Bruno',
        email: '@protonmail.ca',
        phone: '1-358-612-6172',
        status: 'B',
      },
      {
        firstSurname: 'Calhoun',
        lastSurname: 'Rivers',
        name: 'Mary',
        email: '@protonmail.ca',
        phone: '1-548-732-8236',
        status: 'A',
      },
      {
        firstSurname: 'Richards',
        lastSurname: 'Harris',
        name: 'Lance',
        email: '@outlook.com',
        phone: '1-786-177-4385',
        status: 'B',
      },
      {
        firstSurname: 'Arnold',
        lastSurname: 'Williamson',
        name: 'Ria',
        email: '@google.ca',
        phone: '(844) 823-9414',
        status: 'B',
      },
      {
        firstSurname: 'Baxter',
        lastSurname: 'Blankenship',
        name: 'Hamilton',
        email: '@protonmail.ca',
        phone: '(646) 474-2769',
        status: 'A',
      },
      {
        firstSurname: 'Hansen',
        lastSurname: 'Bond',
        name: 'William',
        email: '@yahoo.com',
        phone: '(352) 483-1282',
        status: 'B',
      },
      {
        firstSurname: 'Hill',
        lastSurname: 'Leach',
        name: 'Pearl',
        email: '@aol.org',
        phone: '1-527-733-1975',
        status: 'B',
      },
      {
        firstSurname: 'Rios',
        lastSurname: 'Caldwell',
        name: 'Vanna',
        email: '@hotmail.net',
        phone: '(837) 831-6610',
        status: 'A',
      },
      {
        firstSurname: 'Mcneil',
        lastSurname: 'Estes',
        name: 'Maris',
        email: '@google.couk',
        phone: '1-302-203-1457',
        status: 'A',
      },
      {
        firstSurname: 'Johnston',
        lastSurname: 'Patterson',
        name: 'Jenette',
        email: '@outlook.ca',
        phone: '(766) 724-1566',
        status: 'A',
      },
      {
        firstSurname: 'Sanchez',
        lastSurname: 'Townsend',
        name: 'Dominique',
        email: '@hotmail.ca',
        phone: '(617) 238-9626',
        status: 'A',
      },
      {
        firstSurname: 'Decker',
        lastSurname: 'Park',
        name: 'Nicholas',
        email: '@protonmail.org',
        phone: '1-358-359-3337',
        status: 'A',
      },
      {
        firstSurname: 'Hoover',
        lastSurname: 'Sampson',
        name: 'Brenden',
        email: '@google.ca',
        phone: '1-316-694-3478',
        status: 'B',
      },
      {
        firstSurname: 'Wise',
        lastSurname: 'Bean',
        name: 'Deborah',
        email: '@icloud.com',
        phone: '1-331-619-1288',
        status: 'A',
      },
      {
        firstSurname: 'Gross',
        lastSurname: 'Medina',
        name: 'Logan',
        email: '@icloud.couk',
        phone: '(660) 431-9762',
        status: 'A',
      },
      {
        firstSurname: 'Hurst',
        lastSurname: 'Holland',
        name: 'Griffin',
        email: '@hotmail.edu',
        phone: '1-414-288-5157',
        status: 'A',
      },
      {
        firstSurname: 'Cooper',
        lastSurname: 'Pennington',
        name: 'Malcolm',
        email: '@outlook.org',
        phone: '(304) 528-0729',
        status: 'A',
      },
      {
        firstSurname: 'Nash',
        lastSurname: 'Hensley',
        name: 'Patience',
        email: '@aol.edu',
        phone: '(846) 208-6703',
        status: 'A',
      },
      {
        firstSurname: 'Todd',
        lastSurname: 'Lucas',
        name: 'Leroy',
        email: '@outlook.ca',
        phone: '(281) 391-8338',
        status: 'B',
      },
      {
        firstSurname: 'Morrow',
        lastSurname: 'Adams',
        name: 'Austin',
        email: '@hotmail.org',
        phone: '1-627-687-6669',
        status: 'A',
      },
      {
        firstSurname: 'Peters',
        lastSurname: 'Alvarado',
        name: 'Beau',
        email: '@outlook.net',
        phone: '1-671-761-6202',
        status: 'B',
      },
      {
        firstSurname: 'Koch',
        lastSurname: 'Langley',
        name: 'Chaney',
        email: '@protonmail.edu',
        phone: '1-321-156-7383',
        status: 'A',
      },
      {
        firstSurname: 'Yates',
        lastSurname: 'Johnston',
        name: 'Timon',
        email: '@protonmail.couk',
        phone: '(192) 774-5050',
        status: 'A',
      },
      {
        firstSurname: 'Petersen',
        lastSurname: 'Mullen',
        name: 'Cedric',
        email: '@yahoo.com',
        phone: '1-282-162-0275',
        status: 'B',
      },
      {
        firstSurname: 'Clemons',
        lastSurname: 'Dejesus',
        name: 'Reed',
        email: '@yahoo.edu',
        phone: '(726) 738-4776',
        status: 'B',
      },
      {
        firstSurname: 'Knight',
        lastSurname: 'Carver',
        name: 'Vance',
        email: '@hotmail.ca',
        phone: '(927) 386-5187',
        status: 'B',
      },
      {
        firstSurname: 'Zimmerman',
        lastSurname: 'Davenport',
        name: 'India',
        email: '@google.net',
        phone: '(288) 464-3739',
        status: 'B',
      },
      {
        firstSurname: 'Sosa',
        lastSurname: 'Paul',
        name: 'Christopher',
        email: '@aol.couk',
        phone: '1-248-108-4478',
        status: 'B',
      },
      {
        firstSurname: 'Salas',
        lastSurname: 'Holt',
        name: 'Aladdin',
        email: '@aol.couk',
        phone: '1-265-864-8697',
        status: 'B',
      },
      {
        firstSurname: 'Jensen',
        lastSurname: 'Bell',
        name: 'Burke',
        email: '@hotmail.net',
        phone: '(749) 531-2981',
        status: 'A',
      },
      {
        firstSurname: 'Henry',
        lastSurname: 'Golden',
        name: 'Stewart',
        email: '@hotmail.org',
        phone: '1-527-924-5713',
        status: 'B',
      },
      {
        firstSurname: 'Mcgowan',
        lastSurname: 'Clemons',
        name: 'Dai',
        email: '@google.com',
        phone: '1-389-433-8838',
        status: 'B',
      },
      {
        firstSurname: 'Woodard',
        lastSurname: 'Simpson',
        name: 'Adria',
        email: '@google.edu',
        phone: '1-788-858-7699',
        status: 'B',
      },
      {
        firstSurname: 'Battle',
        lastSurname: 'Nixon',
        name: 'Uma',
        email: '@aol.couk',
        phone: '(961) 564-8177',
        status: 'A',
      },
      {
        firstSurname: 'Gardner',
        lastSurname: 'Burris',
        name: 'Hedda',
        email: '@google.couk',
        phone: '(264) 491-1686',
        status: 'A',
      },
      {
        firstSurname: 'Herrera',
        lastSurname: 'Greer',
        name: 'Harper',
        email: '@aol.couk',
        phone: '(636) 749-7355',
        status: 'B',
      },
      {
        firstSurname: 'Kent',
        lastSurname: 'Yates',
        name: 'Jacob',
        email: '@hotmail.edu',
        phone: '(416) 457-1197',
        status: 'B',
      },
      {
        firstSurname: 'Flores',
        lastSurname: 'Case',
        name: 'Barclay',
        email: '@aol.couk',
        phone: '(788) 239-8284',
        status: 'A',
      },
      {
        firstSurname: 'Bray',
        lastSurname: 'Montgomery',
        name: 'Hilary',
        email: '@yahoo.edu',
        phone: '(538) 871-6368',
        status: 'A',
      },
      {
        firstSurname: 'Peterson',
        lastSurname: 'Calhoun',
        name: 'Willa',
        email: '@hotmail.net',
        phone: '(813) 374-9662',
        status: 'A',
      },
      {
        firstSurname: 'Craft',
        lastSurname: 'Solis',
        name: 'Holmes',
        email: '@aol.com',
        phone: '1-792-617-5580',
        status: 'B',
      },
      {
        firstSurname: 'Miller',
        lastSurname: 'Blackburn',
        name: 'Sade',
        email: '@google.org',
        phone: '(715) 291-1368',
        status: 'B',
      },
      {
        firstSurname: 'Higgins',
        lastSurname: 'Roberson',
        name: 'India',
        email: '@hotmail.net',
        phone: '(484) 126-8757',
        status: 'B',
      },
      {
        firstSurname: 'Haney',
        lastSurname: 'Rodgers',
        name: 'Kellie',
        email: '@outlook.org',
        phone: '(738) 688-6663',
        status: 'B',
      },
      {
        firstSurname: 'Bridges',
        lastSurname: 'Cardenas',
        name: 'Laurel',
        email: '@protonmail.com',
        phone: '(729) 423-2691',
        status: 'B',
      },
      {
        firstSurname: 'Boyer',
        lastSurname: 'Hickman',
        name: 'Joseph',
        email: '@yahoo.couk',
        phone: '(378) 189-3125',
        status: 'B',
      },
    ],
    []
  );

  return rows;
}
